version: '2.6'
volumes:
  gocache: {}
  gomod: {}
  source: {}
services:
  unit-tests:
    image: golang:1.21-alpine
    volumes:
      - $PWD/app:/go/app/src
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
    working_dir: /go/app/src
    entrypoint: [ "go", "test", "-failfast", "./..." ]
  build:
    image: golang:1.21-alpine
    volumes:
      - $PWD/out:/out
      - gocache:/root/.cache/go-build
      - gomod:/go/pkg/mod
      - source:/go/app/src
    environment:
      - GOOS
      - GOARCH
    working_dir: /go/app/src
    entrypoint: [ "go", "build", "-o", "/out/exporter-$VERSION-$GOOS-$GOARCH", "main.go" ]
  copy-source:
    image: bash:5
    volumes:
      - $PWD/app:/go/app/src
      - source:/src
    command:
       - -c
       - |
         cp -R /go/app/src / &&
         sed -i "s;%%VER_CHANGED_BY_MAKE%%;$VERSION;g" /src/exporter/exporter.go &&
         sed -i "s;%%SHA_CHANGED_BY_MAKE%%;$COMMIT_SHA;g" /src/exporter/exporter.go
